[phases.setup]
nixPkgs = ['python39', 'postgresql']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    '. /opt/venv/bin/activate && python manage.py collectstatic --noinput'
]

[start]
cmd = '. /opt/venv/bin/activate && python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 300 mofa_task_tracker.wsgi:application'
